
C++线程库定义在<thread>中，启动新线程现在是件很简单的事情了。可以通过多种方式指定新线程中需要执行的内容，可以让新线程执行一个全局函数、函数对象的operator()、一个Lambda表达式，甚至是某个类实例的成员函数。以下各节给出一些简单的示例。

\mySubsubsection{27.2.1}{使用函数指针的线程}

Windows上的CreateThread()、\_beginthread()等函数，以及pthreads库中的pthread\_create()，都要求线程函数只有一个参数，而标准std::thread使用的函数可以有任意数量的参数。

假设有一个counter()函数，接受两个整数：第一个代表ID，第二个代表函数应循环的迭代次数。函数体是一个循环，循环给定的迭代次数。每次迭代中，向标准输出打印一条消息。

\begin{cpp}
void counter(int id, int numIterations)
{
    for (int i { 0 }; i < numIterations; ++i) {
        println("Counter {} has value {}", id, i);
    }
}
\end{cpp}

可以使用std::thread启动多个执行此函数的线程。创建一个线程t1，执行带有参数1和6的counter()：

\begin{cpp}
thread t1 { counter, 1, 6 };
\end{cpp}

线程类的构造函数是一个可变参数模板，接受任意数量的参数。第一个参数是要在新线程中执行的可调用对象（例如:函数指针——这个例子中，是指向函数counter()的指针），后续参数在启动线程执行时，传递给这些参数给可调用对象。

如果线程对象表示或曾表示系统中的活动线程，则称该线程对象可汇入。即使线程已经执行完毕，线程对象仍保持可汇入状态。默认构造的线程对象不可汇入。可汇入的线程对象销毁之前，需要使用join()或detach()。join()为阻塞调用：等待线程完成其工作。对detach()的调用将线程对象与其底层的OS线程分离，使OS线程独立运行。这两个成员函数都会导致线程变为不可汇入。如果销毁一个可汇入的线程对象，析构函数会调用std::terminate()，这将终止所有线程和应用程序本身。这种行为的原因是，销毁一个没有汇入的线程肯定是一个错误，终止程序是库指示问题的最佳方式。

以下代码启动两个线程执行counter()函数。启动线程后，对两个线程调用join()。

\begin{cpp}
thread t1 { counter, 1, 6 };
thread t2 { counter, 2, 4 };
t1.join();
t2.join();
\end{cpp}

此例的可能输出如下所示：

\begin{shell}
Counter 2 has value 0
Counter 1 has value 0
Counter 1 has value 1
Counter 1 has value 2
Counter 1 has value 3
Counter 1 has value 4
Counter 1 has value 5
Counter 2 has value 1
Counter 2 has value 2
Counter 2 has value 3
\end{shell}

系统上的输出将不同，并且每次运行时都可能不同。因为两个线程同时执行counter()函数，所以输出取决于机器的处理器数量和操作系统的线程调度。

不同线程中使用print()或println()是线程安全的，不会导致数据竞争。如果将counter()中的单个println()语句更改为以下内容：

\begin{cpp}
print("Counter {} has value {}", id, i);
println("");
\end{cpp}

或:

\begin{cpp}
cout << format("Counter {} has value {}", id, i) << endl;
\end{cpp}

或:

\begin{cpp}
cout << format("Counter {} has value {}", id, i);
cout << endl;
\end{cpp}

即使仍然没有数据竞争，不同线程的输出可能会交错！所以输出可能会混合在一起：

\begin{shell}
Counter 1 has value 0Counter 2 has value 0

Counter 2 has value 1
Counter 2 has value 2Counter 1 has value 1
...
\end{shell}

这可以使用本章后面讨论的同步机制来修复。

\begin{myNotic}{NOTE}
线程函数参数总会复制到线程的某个内部存储中，使用<functional>中的std::ref()或std::cref()可按引用传递。
\end{myNotic}

\mySubsubsection{27.2.2}{使用函数对象的线程}

除了使用函数指针，还可以使用函数对象在线程中执行。前一节的函数指针中，将信息传递给线程的唯一方式是通过函数传递参数。使用函数对象，可以为的函数对象类添加数据成员，可以初始化并按想要的方式使用。以下示例首先定义了一个名为Counter的类，有两个数据成员：一个ID和循环的迭代次数。两个变量都通过构造函数初始化。为了使Counter类成为一个函数对象，需要实现operator()。operator()的实现与前一节中的counter()函数相同。以下是实现代码：

\begin{cpp}
class Counter
{
    public:
        explicit Counter(int id, int numIterations)
            : m_id { id }, m_numIterations { numIterations } { }

        void operator()() const
        {
            for (int i { 0 }; i < m_numIterations; ++i) {
                println("Counter {} has value {}", m_id, i);
            }
        }
    private:
        int m_id { 0 };
        int m_numIterations { 0 };
};
\end{cpp}

以下代码片段演示了使用函数对象初始化线程的两种技术。第一种技术使用统一初始化语法，使用其构造函数参数创建Counter的实例，并将其放在大括号之间传递给线程构造函数。第二种技术定义了Counter的命名实例，并将这个命名实例传递给线程类的构造函数。

\begin{cpp}
// Using uniform initialization syntax.
thread t1 { Counter { 1, 20 } };

// Using named variable.
Counter c { 2, 12 };
thread t2 { c };

// Wait for threads to finish.
t1.join();
t2.join();
\end{cpp}

\begin{myNotic}{NOTE}
函数对象总会复制到线程的某个内部存储中。如果想对特定实例的operator()上执行，而不是在副本上执行，应该使用<functional>中的std::ref()或std::cref()按引用传递实例：

\begin{cpp}
Counter c { 2, 12 };
thread t2 { ref(c) };
\end{cpp}

然而，由于t2现在有对c的引用，如果在t2完成并加入之前从主线程读取或写入c的内容，将会导致数据竞争（从而产生未定义行为）。
\end{myNotic}

\mySubsubsection{27.2.3}{使用Lambda的线程}

Lambda表达式与标准C++线程库非常契合。以下示例启动一个线程执行给定的Lambda表达式：

\begin{cpp}
int id { 1 };
int numIterations { 5 };
thread t1 { [id, numIterations] {
        for (int i { 0 }; i < numIterations; ++i) {
            println("Counter {} has value {}", id, i);
        }
} };
t1.join();
\end{cpp}

\mySubsubsection{27.2.4}{使用成员函数指针的线程}

可以指定一个类的成员函数在线程中执行。以下示例定义了一个带有process()成员函数的基本Request类，main()函数创建Request类的一个实例，并启动一个新线程，该线程执行Request实例req的process()成员函数。

\begin{cpp}
class Request
{
    public:
        explicit Request(int id) : m_id { id } { }
        void process() { println("Processing request {}", m_id); }
    private:
        int m_id { 0 };
};

int main()
{
    Request req { 100 };
    thread t { &Request::process, &req };
    t.join();
}
\end{cpp}

使用这种技术，可在一个单独的线程中对特定对象执行成员函数。如果其他线程正在访问同一个对象，需要确保以线程安全的方式发生，以避免数据竞争。可以使用同步机制，使应用线程安全，这会在后续内容中介绍。

\mySubsubsection{27.2.5}{线程局部存储}

C++标准支持线程局部存储。使用一个名为thread\_local的关键字，可以标记变量为线程局部，每个线程将有自己的唯一副本。对于每个线程，变量初始化一次。以下代码定义了两个全局变量，k和n。每个线程中都会共享有一个k的副本，而每个线程都有自己唯一的n。

\begin{cpp}
int k;
thread_local int n;
\end{cpp}

以下代码片段验证了这一点。threadFunction()打印当前k和n的值，然后递增它们。main()函数启动一个第一个线程，等待它完成，然后启动第二个线程。

\begin{cpp}
void threadFunction(int id)
{
    println("Thread {}: k={}, n={}", id, k, n);
    ++n;
    ++k;
}

int main()
{
    thread t1 { threadFunction, 1 }; t1.join();
    thread t2 { threadFunction, 2 }; t2.join();
}
\end{cpp}

从以下输出中，很明显k只有一个实例在所有线程之间共享，而每个线程都有自己的n。

\begin{shell}
Thread 1: k=0, n=0
Thread 2: k=1, n=0
\end{shell}

前面的段落展示了thread\_local如何用于全局变量，也适用于类的静态数据成员和函数的静态局部变量。函数内部，并且仅在函数内部，将变量声明为thread\_local意味着静态，需要明确这一点。这里有一些例子：

\begin{cpp}
static thread_local int x1; // OK, internal linkage (See Chapter 11)
thread_local int x2; // OK, external linkage (See Chapter 11)

class Foo
{
    static thread_local int x3; // OK
    thread_local int x4; // Error!
};

void f()
{
    static thread_local int x5; // OK
    thread_local int x6; // OK, implicitly static!
}
\end{cpp}

\mySubsubsection{27.2.6}{取消线程}

C++标准不包括从另一个线程取消运行线程的机制，一个（部分）解决方案是使用下一节讨论的jthread类。如果这不是一个选项，实现的最佳方法就是提供一个线程之间约定的通信机制。最简单的机制是拥有一个共享变量，目标线程定期检查以确定是否应该终止。其他线程可以设置这个共享变量以间接指示线程关闭，这里需要谨慎，因为多个线程正在访问这个共享变量，至少有一个线程正在写入共享变量。为了保证线程安全，建议使用原子变量或条件变量，这两者都在本章后面讨论。

\mySubsubsection{27.2.7}{自动汇入线程}

如果一个可汇入的线程实例销毁，C++运行时会调用std::terminate()来终止应用程序。<thread>还定义了std::jthread，与thread几乎完全相同，除了：

\begin{itemize}
\item
析构函数中自动汇入。

\item
支持协作取消。
\end{itemize}

\mySamllsection{协作取消}

jthread的取消支持称为协作取消，因为支持取消的线程需要定期检查是否需要取消自身。给出示例之前，需要介绍两个在<stop\_token>中定义的重要类

\begin{itemize}
\item
std::stop\_token: 支持主动检查取消请求。一个可取消的线程需要定期在一个stop\_token上调用stop\_requested()来找出它是否需要停止工作。stop\_token可以与condition\_variable\_any一起使用，这样线程可以在需要停止时唤醒。

\item
std::stop\_source: 用于请求线程取消其执行。通过在stop\_source上调用request\_stop()成员函数来完成的。如果stop\_source用于请求取消，则该取消请求对所有关联的stop\_source和stop\_token可见。可以使用stop\_requested()成员函数来检查，是否已经请求了停止。
\end{itemize}

如果有一个jthread实例，可以通过使用get\_stop\_token()和get\_stop\_source()成员函数来访问其stop\_token和stop\_source。此外，传递给jthread构造函数的可调用对象，可以将其第一个参数作为stop\_token。

以下代码定义了一个threadFunction()可调用对象，接受一个stop\_token作为其第一个参数。因为协作取消，所以这个线程函数的主体使用这个stop\_token来检查否需要取消。这段代码使用std::this\_thread::sleep\_for()在每个循环中引入一个小延迟，sleep\_for()的参数是一个std::chrono::duration。

\begin{cpp}
void threadFunction(stop_token token, int id)
{
    while (!token.stop_requested()) {
        println("Thread {} doing some work.", id);
        this_thread::sleep_for(500ms);
    }
    println("Stop requested for thread {}.", id);
}
\end{cpp}

以下main()函数创建两个jthread实例来执行threadFunction()，休眠两秒钟，写入一个消息表示结束，并请求两个线程停止：

\begin{cpp}
int main()
{
    jthread job1 { threadFunction, 1 };
    jthread job2 { threadFunction, 2 };

    this_thread::sleep_for(2s);
    println("main() is ending.");

    job1.request_stop();
    job2.request_stop();
}
\end{cpp}

此程序的可能输出，如下所示：

\begin{shell}
Thread 2 doing some work.
Thread 1 doing some work.
Thread 2 doing some work.
Thread 1 doing some work.
Thread 2 doing some work.
Thread 1 doing some work.
Thread 2 doing some work.
Thread 1 doing some work.
main() is ending.
Stop requested for thread 2.
Stop requested for thread 1.
\end{shell}

jthread的析构函数会自动请求其线程停止执行，然后汇入，所以前面的main()函数可以通过省略两个request\_stop()调用进行简化。

\mySubsubsection{27.2.8}{从线程中获取结果}

启动新线程相当简单，但我们可能对线程产生的结果感兴趣。例如，线程执行一些数学计算，很希望线程完成时获取结果。一种方法是将结果变量的指针或引用传递给线程，线程在其中存储结果。另一种技术是将结果存储在函数对象类的类数据成员中，可以在线程执行完成后稍后获取。使用std::ref()，将函数对象按引用传递给jthread构造函数时才有效。以下是示例：

\begin{cpp}
class Calculator
{
    public:
        explicit Calculator(int a, int b) : m_a { a }, m_b { b } {}
        void operator()() { result = m_a * m_b; }
        int getResult() const { return result; }
    private:
        int m_a { 0 };
        int m_b { 0 };
        int result { 0 };
};

int main()
{
    Calculator calculator { 21, 2 };
    jthread job { ref(calculator) };
    job.join();
    println("21*2 = {}", calculator.getResult());
}
\end{cpp}

正确地输出为：

\begin{shell}
21*2 = 42
\end{shell}

如果不使用ref()，并且像以下这样初始化job，那么输出将是21*2 = 0：

\begin{cpp}
jthread job { calculator };
\end{cpp}

还有一个更简单的机制可以从线程中获取结果：future。future也使处理线程内的错误变得更加容易，将在本章后面介绍。

\mySubsubsection{27.2.9}{复制和重抛异常}

C++中整个异常机制在单一线程中运行得相当好。每个线程都可以抛出自己的异常，但需要在各自的线程中进行捕获。如果一个线程抛出一个异常，且该异常在原线程中没有捕获，C++运行时将调用std::terminate()，这将终止整个应用程序。一个线程抛出的异常不能在另一个线程捕获，这在结合异常处理和多线程编程时，引入了许多问题。

如果没有标准线程库，跨线程优雅地处理异常是相当困难的(可能的话)。标准线程库通过以下与异常相关的函数解决了这个问题。这些函数不仅适用于std::exception，还适用于其他类型的异常、整数、字符串、自定义异常等：

\begin{itemize}
\item
\begin{cpp}
exception_ptr current_exception() noexcept;
\end{cpp}

旨在在catch块中调用。返回一个指向当前正在处理的异常的exception\_ptr对象，或者是对当前正在处理的异常的复制。如果没有异常正在处理，则返回一个空的exception\_ptr对象。这个引用的异常对象是引用计数的，类似于std::shared\_ptr，只要有一个对象类型为exception\_ptr的引用，就能保持有效。

\item
\begin{cpp}
[[noreturn]] void rethrow_exception(exception_ptr p);
\end{cpp}

重新抛出由exception\_ptr参数引用的异常（该参数不能为null）。重新抛出引用异常不必在生成引用异常的原始线程中进行，这使得这种特性非常适合跨不同线程处理异常。由于[[noreturn]]属性，该函数永远不会以正常方式返回。

\item
\begin{cpp}
template<class E> exception_ptr make_exception_ptr(E e) noexcept;
\end{cpp}

创建指向给定异常对象复制的exception\_ptr对象：

\begin{cpp}
try { throw e; }
catch(...) { return current_exception(); }
\end{cpp}
\end{itemize}

来看看如何使用这些函数跨不同线程处理异常。以下代码定义了一个函数，该函数执行一些工作并抛出一个异常。这个函数最终将在独立线程中运行。

\begin{cpp}
void doSomeWork()
{
    for (int i { 0 }; i < 5; ++i) { println("{}", i); }
    println("Thread throwing a runtime_error exception...");
    throw runtime_error { "Exception from thread" };
}
\end{cpp}

以下threadFunc()函数将调用前面的函数包裹在一个try/catch块中，捕获doSomeWork()抛出的所有异常。向threadFunc()函数提供单一的参数，该参数的类型是exception\_ptr\&。捕获到异常时，使用current\_exception()函数获取正在处理的异常的引用，然后将其赋值给exception\_ptr参数。之后，线程正常退出。

\begin{cpp}
void threadFunc(exception_ptr& err)
{
    try {
        doSomeWork();
    } catch (...) {
        println("Thread caught exception, returning exception...");
        err = current_exception();
    }
}
\end{cpp}

以下doWorkInThread()函数在主线程内部调用，用来创建一个新线程并开始在其中执行threadFunc()，向threadFunc()提供一个exception\_ptr类型的对象引用作为参数。当线程已创建，doWorkInThread()函数可通过使用join()成员函数等待线程完成，之后检查错误对象。由于exception\_ptr是NullablePointer类型，就可以使用if语句来检查。如果是非null值，异常将在当前线程中重新抛出，这个例子中是主线程。因为在主线程中重新抛出异常，所以异常已经从一个线程转移到另一个线程。

\begin{cpp}
void doWorkInThread()
{
    exception_ptr error;
    // Launch thread.
    jthread t { threadFunc, ref(error) };
    // Wait for thread to finish.
    t.join();
    // See if thread has thrown any exception.
    if (error) {
        println("Main thread received exception, rethrowing it...");
        rethrow_exception(error);
    } else {
        println("Main thread did not receive any exception.");
    }
}
\end{cpp}

main()函数相当简单。调用doWorkInThread()，并将调用包裹在一个try/catch块中，以捕获由doWorkInThread()创建的线程抛出的异常。

\begin{cpp}
int main()
{
    try {
        doWorkInThread();
    } catch (const exception& e) {
        println("Main function caught: '{}'", e.what());
    }
}
\end{cpp}

输出为：

\begin{shell}
0
1
2
3
4
Thread throwing a runtime_error exception...
Thread caught exception, returning exception...
Main thread received exception, rethrowing it...
Main function caught: 'Exception from thread'
\end{shell}

这里main()函数使用join()，无论是显式还是隐式地与jthread一起使用，以阻塞主线程并等待线程完成。在实际应用中，可能不想阻塞主线程。在GUI应用程序中，阻塞主线程意味着UI变得无响应。这种情况下，可以使用消息传递范式在线程之间进行通信。例如，之前的threadFunc()函数可以向UI线程发送一个消息，current\_exception()结果的副本可作为参数。



