
\CXXTwentythreeLogo{-40}{10}

每当函数A()调用另一个函数B()时，都会记录传递给B()的参数，以及函数完成时需要返回的位置信息。B()的执行可能会再次调用另一个函数C()，以此类推。所有这些信息都会记录在栈跟踪（也称为调用栈）的帧中。对于每个函数调用，都会在栈跟踪中添加一个新帧。当函数执行完毕时，其帧会从栈跟踪中移除。程序执行时，栈跟踪都能知道确切是通过哪些函数调用到达当前正在执行的函数，这样的信息对于找到并修复程序中的错误至关重要，第31章详细介绍了调试。本节讨论了标准库提供的用于处理栈跟踪的功能，以及如何与自定义异常结合使用，这个特性只有在C++23之后才能使用。

\mySubsubsection{14.7.1}{栈跟踪库}

栈跟踪库定义在<stacktrace>中,可以使用静态成员函数std::stacktrace::current()取栈跟踪信息。如果想要跳过栈跟踪顶部的某些帧，可以向current()传递一个整数。下一个部分将给出一个这样的例子。有了栈跟踪，就可以轻松地使用print()或println()将其打印到控制台，也可以使用std::to\_string()将栈跟踪转换为字符串。这里是一个例子：

\begin{cpp}
void handleStackTrace(const stacktrace& trace)
{
    println(" Stack trace information:");
    println("   There are {} frames in the stack trace.", trace.size());
    println("   Here are all the frames:");
    println("---------------------------------------------------------");
    println("{}", trace);
    // If the above statement doesn't work yet, you can use the following:
    //println("{}", to_string(trace));
    println("---------------------------------------------------------");
}

void C()
{
    println("Entered C().");
    handleStackTrace(stacktrace::current());
}

void B() { println("Entered B()."); C(); }
void A() { println("Entered A()."); B(); }

int main()
{
    A();
}
\end{cpp}

使用Microsoft Visual C++编译并在Windows上运行，输出类似于以下内容。为了防止换行，就截断路径名。文件01\_stacktrace.cpp是我们的代码，文件exe\_common.inl和exe\_main.cpp隶属于Visual C++运行时。最后两个帧kernel32和ntdll是Windows内核的一部分：

\begin{shell}
Entered A().
Entered B().
Entered C().
  Stack trace information:
    There are 10 frames in the stack trace.
    Here are all the frames:
---------------------------------------------------------
0> D:\...\01_stacktrace.cpp(20): TestApp!C+0x77
1> D:\...\01_stacktrace.cpp(27): TestApp!B+0x61
2> D:\...\01_stacktrace.cpp(33): TestApp!A+0x61
3> D:\...\01_stacktrace.cpp(38): TestApp!main+0x20
4> D:\...\exe_common.inl(79): TestApp!invoke_main+0x39
5> D:\...\exe_common.inl(288): TestApp!__scrt_common_main_seh+0x12E
6> D:\...\exe_common.inl(331): TestApp!__scrt_common_main+0xE
7> D:\...\exe_main.cpp(17): TestApp!mainCRTStartup+0xE
8> KERNEL32!BaseThreadInitThunk+0x1D
9> ntdll!RtlUserThreadStart+0x28
---------------------------------------------------------
\end{shell}

可以遍历栈跟踪的各个帧，并查询每个帧的信息。帧使用std::stacktrace\_entry类表示，有以下成员函数：

\begin{itemize}
\item
description(): 返回帧描述

\item
source\_file() 和  source\_line(): 包含帧的源文件名和源文件中的行号
\end{itemize}

下面的handleStackTrace()的实现，并没有一次性打印整个栈跟踪，而是遍历了每个帧，只输出了每个帧的描述。

\begin{cpp}
void handleStackTrace(const stacktrace& trace)
{
    println(" Stack trace information:");
    println(" There are {} frames in the stack trace.", trace.size());
    println(" Here are the descriptions of all the frames:");
    for (unsigned index { 0 }; auto&& frame : trace) {
        println(" {} -> {}", index++, frame.description());
    }
}
\end{cpp}

输出如下所示：

\begin{shell}
Entered A().
Entered B().
Entered C().
  Stack trace information:
    There are 10 frames in the stack trace.
    Here are the descriptions of all the frames:
      0 -> TestApp!C+0x77
      1 -> TestApp!B+0x61
      2 -> TestApp!A+0x61
      3 -> TestApp!main+0x20
      4 -> TestApp!invoke_main+0x39
      ... <snip> ...
\end{shell}

\mySubsubsection{14.7.2}{自动嵌入堆栈跟踪的异常}

可以扩展之前关于source\_location的MyException类，以跟踪堆栈(除了源位置之外)。

\begin{cpp}
class MyException : public exception
{
    public:
        explicit MyException(string message,
        source_location location = source_location::current())
            : m_message { move(message) }
            , m_location { move(location) }
            , m_stackTrace { stacktrace::current(1) } // 1 means skip top frame.
        { }

        const char* what() const noexcept override { return m_message.c_str(); }
        virtual const source_location& where() const noexcept{ return m_location; }
        virtual const stacktrace& how() const noexcept { return m_stackTrace; }
    private:
        string m_message;
        source_location m_location;
        stacktrace m_stackTrace;
};
\end{cpp}

注意，构造函数将1传递给stacktrace::current()，以跳过堆栈跟踪的顶部帧。这个顶部帧将是MyException构造函数，我们对此不感兴趣。我们只对导致创建这个MyException实例的堆栈跟踪感兴趣，所以可以这样测试这个新异常类：

\begin{cpp}
void doSomething()
{
    throw MyException { "Throwing MyException." };
}

int main()
{
    try {
        doSomething();
    } catch (const MyException& e) {
        // Print exception description + location where exception was raised.
        const auto& location { e.where() };
        println(cerr, "Caught: '{}' at line {} in {}.",
            e.what(), location.line(), location.function_name());

        // Print the stack trace at the point where the exception was raised.
        println(cerr, " Stack trace:");
        for (unsigned index { 0 }; auto&& frame : e.how()) {
            const string& fileName { frame.source_file() };
            println(cerr, " {}> {}, {}({})", index++, frame.description(),
                (fileName.empty() ? "n/a" : fileName), frame.source_line());
        }
    }
}
\end{cpp}

使用Microsoft Visual C++编译并在Windows上运行时，输出类似于以下内容。以简洁为主，只显示堆栈跟踪的顶部两个相关信息，跳过了Visual C++运行时或Windows本身内部的堆栈信息。

\begin{shell}
Caught: 'Throwing MyException.' at line 30 in void __cdecl doSomething(void).
  Stack trace:
    0> TestApp!doSomething+0xD2, D:\...\03_CustomExceptionWithStackTrace.cpp(30)
    1> TestApp!main+0x4D, D:\...\03_CustomExceptionWithStackTrace.cpp(36)
    ... <snip> ...
\end{shell}

\begin{myNotic}{NOTE}
如果使用自定义异常，请在其中嵌入堆栈跟踪，以便调试错误。
\end{myNotic}













